### ISSUE TITLE
Get permission from OCTranspo to deploy on busses

### ISSUE THREAD

**Issue by SirPolaris** [Citizen-Group/BumpTrax#18]
**Part of:** Bus Deployment
**Prio:** High

For this project to be a shining success, we will need permission to test our product on the busses.

**Expected results:** 
- [ ] Prepare the hardware #19
- [ ] Create a demo presentation #20
- [ ] Start the conversation with OCTranspo #21
- [ ] Demo and present our plan #22
