### ISSUE TITLE
Develop the algorithm to determine road health

### ISSUE THREAD

**Issue by SirPolaris** [Citizen-Group/BumpTrax#8]
**Requested by:** Citizen for City Automation
**Part of:** Algorithms 
**Prio:** Medium
**Requires:** #14, #15 

For the success of this project we require an algorithm that can produce an reliable and accurate output, that provides a general indication of "road health/quality" in an automatic function.

Road health differs from defect detection, but it's within the same family. The adjustment to this algorithm over the defect detecting one, is that this would sample the overall "ride feel" and determine via weight and variables if the road is acceptable. Defect detection would reduce the quality score considerably, but this algorithm needs to factor in time (distance).

10 potholes every 30 minutes is not the same as 5 in short concession. Also every defect has a severity attached, and one ultra severe would trump any other issues or benefits to the road.

**Implementation:**
- Develop a modular mathematical formula that can be deployed on devices like a PI or cellphone
- The output needs to provide a meaningful common metric. Suggestions like a 0 to 1 value for "destroyed to perfect" or "no defects, high quality ride to many defects, extremely uncomfortable ride"
- The values used to set what is "bad" and what is "acceptable" must be variables.
- The algorithm should have a "offset" so we can shift up or down the scale, of what is acceptable.

**Expected results:** 
- [ ] Must be fully automated and require no human intervention
- [ ] Must have better then 80% accuracy for detection
- [ ] Must have no false positives 
- [ ] Output provides a meaningful, common metric to compare all roads against

**References:**
#1, #15, #13
